# Generated by Django 5.2.5 on 2025-10-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_create', 'can create'), ('can_change_book', 'Can edit book details'), ('can_delete_book', 'Can delete a book'), ('can_view_book', 'Can view book')]},
        ),
    ]
